In [1]:
import tensorflow as tf
import numpy as np
import random

In [ ]:
"""题目1. 数组排序
   
    要求: 给定以下多维数组，沿第3列，对整个数组进行排序（第三列最终结果从小到大或从大到小均可）.
   
    示例:
        给定:
            [[5, 2, 6, 4],
             [1, 4, 3, 6],
             [0, 1, 10, 2],
             [1, 1, 1, 1]]
        期望输出:
            [[1, 1, 1, 1],
             [1, 4, 3, 6],
             [5, 2, 6, 4],
             [0, 1, 10, 2]]
"""

In [2]:
"""题目1. 作答"""
arr = np.random.randint(0,20,size=[8,6])
"""
作答区
"""

'\n作答区\n'

In [3]:
arr

array([[ 4,  2,  0,  8,  0,  4],
       [15,  1, 18,  5,  0,  4],
       [ 5, 16,  5, 11, 13,  4],
       [10, 12,  6, 15, 11, 12],
       [18, 14, 13, 10, 18,  2],
       [15,  0, 16,  2, 13,  2],
       [ 9,  5, 19,  6,  3,  9],
       [15,  9, 13, 15,  7, 16]])

In [6]:
index = np.argsort(arr, axis=0)
index

array([[0, 5, 0, 5, 0, 4],
       [2, 1, 2, 1, 1, 5],
       [6, 0, 3, 6, 6, 0],
       [3, 6, 4, 0, 7, 1],
       [1, 7, 7, 4, 3, 2],
       [5, 3, 5, 2, 2, 6],
       [7, 4, 1, 3, 5, 3],
       [4, 2, 6, 7, 4, 7]])

In [12]:
sorted_arr = np.zeros((8, 6))
for i in range(8):
    sorted_arr[i, :] = arr[index[i, 2], :]
sorted_arr
    

array([[ 4.,  2.,  0.,  8.,  0.,  4.],
       [ 5., 16.,  5., 11., 13.,  4.],
       [10., 12.,  6., 15., 11., 12.],
       [18., 14., 13., 10., 18.,  2.],
       [15.,  9., 13., 15.,  7., 16.],
       [15.,  0., 16.,  2., 13.,  2.],
       [15.,  1., 18.,  5.,  0.,  4.],
       [ 9.,  5., 19.,  6.,  3.,  9.]])